name: Build Flutter APK and IPA

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.GERRIT_SSH_KEY }}

      - name: Clone Gerrit repository
        run: git clone ssh://username@gerrit.example.com:29418/project-name.git

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.2'

      - name: Install dependencies
        run: flutter pub get
      - name: Build APK
        run: flutter build apk --release

      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: app-release.apk
          path: build/app/outputs/flutter-apk/app-release.apk

  build-ios:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.GERRIT_SSH_KEY }}

      - name: Clone Gerrit repository
        run: git clone ssh://username@gerrit.example.com:29418/project-name.git

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.2'

      - name: Install dependencies
        run: flutter pub get

      - name: Set up Xcode
        run: sudo xcode-select -s /Applications/Xcode_12.4.app

      - name: Install CocoaPods
        run: |
          brew install cocoapods
          pod install --project-directory=./ios

      - name: Build IPA
        run: flutter build ios --release --no-codesign

      - name: Create IPA
        run: |
          xcodebuild -workspace ios/Runner.xcworkspace -scheme Runner -sdk iphoneos -configuration Release archive -archivePath $PWD/build/Runner.xcarchive
          xcodebuild -exportArchive -archivePath $PWD/build/Runner.xcarchive -exportOptionsPlist ios/exportOptions.plist -exportPath $PWD/build/Runner

      - name: Upload IPA
        uses: actions/upload-artifact@v2
        with:
          name: Runner.ipa
          path: build/Runner/Runner.ipa
